<?php

/******************************************************************************/
/******************************************************************************/

class CRBSCountry
{
	/**************************************************************************/

	function __construct()
	{
		$this->country=CRBSGlobalData::setGlobalData('country',array($this,'init'));
	}
	
    /**************************************************************************/

    function init()
    {
        $country=array
        (
            'AF'                                                                =>  array(__('Afghanistan','car-rental-booking-system')),
            'AX'                                                                =>  array(__('Aland Islands','car-rental-booking-system')),
            'AL'                                                                =>  array(__('Albania','car-rental-booking-system')),
            'DZ'                                                                =>  array(__('Algeria','car-rental-booking-system')),
            'AS'                                                                =>  array(__('American Samoa','car-rental-booking-system')),
            'AD'                                                                =>  array(__('Andorra','car-rental-booking-system')),
            'AO'                                                                =>  array(__('Angola','car-rental-booking-system')),
            'AI'                                                                =>  array(__('Anguilla','car-rental-booking-system')),
            'AQ'                                                                =>  array(__('Antarctica','car-rental-booking-system')),
            'AG'                                                                =>  array(__('Antigua And Barbuda','car-rental-booking-system')),
            'AR'                                                                =>  array(__('Argentina','car-rental-booking-system')),
            'AM'                                                                =>  array(__('Armenia','car-rental-booking-system')),
            'AW'                                                                =>  array(__('Aruba','car-rental-booking-system')),
            'AU'                                                                =>  array(__('Australia','car-rental-booking-system')),
            'AT'                                                                =>  array(__('Austria','car-rental-booking-system')),
            'AZ'                                                                =>  array(__('Azerbaijan','car-rental-booking-system')),
            'BS'                                                                =>  array(__('Bahamas','car-rental-booking-system')),
            'BH'                                                                =>  array(__('Bahrain','car-rental-booking-system')),
            'BD'                                                                =>  array(__('Bangladesh','car-rental-booking-system')),
            'BB'                                                                =>  array(__('Barbados','car-rental-booking-system')),
            'BY'                                                                =>  array(__('Belarus','car-rental-booking-system')),
            'BE'                                                                =>  array(__('Belgium','car-rental-booking-system')),
            'BZ'                                                                =>  array(__('Belize','car-rental-booking-system')),
            'BJ'                                                                =>  array(__('Benin','car-rental-booking-system')),
            'BM'                                                                =>  array(__('Bermuda','car-rental-booking-system')),
            'BT'                                                                =>  array(__('Bhutan','car-rental-booking-system')),
            'BO'                                                                =>  array(__('Bolivia','car-rental-booking-system')),
            'BA'                                                                =>  array(__('Bosnia And Herzegovina','car-rental-booking-system')),
            'BW'                                                                =>  array(__('Botswana','car-rental-booking-system')),
            'BV'                                                                =>  array(__('Bouvet Island','car-rental-booking-system')),
            'BR'                                                                =>  array(__('Brazil','car-rental-booking-system')),
            'IO'                                                                =>  array(__('British Indian Ocean Territory','car-rental-booking-system')),
            'BN'                                                                =>  array(__('Brunei Darussalam','car-rental-booking-system')),
            'BG'                                                                =>  array(__('Bulgaria','car-rental-booking-system')),
            'BF'                                                                =>  array(__('Burkina Faso','car-rental-booking-system')),
            'BI'                                                                =>  array(__('Burundi','car-rental-booking-system')),
            'KH'                                                                =>  array(__('Cambodia','car-rental-booking-system')),
            'CM'                                                                =>  array(__('Cameroon','car-rental-booking-system')),
            'CA'                                                                =>  array(__('Canada','car-rental-booking-system')),
            'CV'                                                                =>  array(__('Cape Verde','car-rental-booking-system')),
            'KY'                                                                =>  array(__('Cayman Islands','car-rental-booking-system')),
            'CF'                                                                =>  array(__('Central African Republic','car-rental-booking-system')),
            'TD'                                                                =>  array(__('Chad','car-rental-booking-system')),
            'CL'                                                                =>  array(__('Chile','car-rental-booking-system')),
            'CN'                                                                =>  array(__('China','car-rental-booking-system')),
            'CX'                                                                =>  array(__('Christmas Island','car-rental-booking-system')),
            'CC'                                                                =>  array(__('Cocos (Keeling) Islands','car-rental-booking-system')),
            'CO'                                                                =>  array(__('Colombia','car-rental-booking-system')),
            'KM'                                                                =>  array(__('Comoros','car-rental-booking-system')),
            'CG'                                                                =>  array(__('Congo','car-rental-booking-system')),
            'CD'                                                                =>  array(__('Congo, Democratic Republic','car-rental-booking-system')),
            'CK'                                                                =>  array(__('Cook Islands','car-rental-booking-system')),
            'CR'                                                                =>  array(__('Costa Rica','car-rental-booking-system')),
            'CI'                                                                =>  array(__('Cote D\'Ivoire','car-rental-booking-system')),
            'HR'                                                                =>  array(__('Croatia','car-rental-booking-system')),
            'CU'                                                                =>  array(__('Cuba','car-rental-booking-system')),
            'CY'                                                                =>  array(__('Cyprus','car-rental-booking-system')),
            'CZ'                                                                =>  array(__('Czech Republic','car-rental-booking-system')),
            'DK'                                                                =>  array(__('Denmark','car-rental-booking-system')),
            'DJ'                                                                =>  array(__('Djibouti','car-rental-booking-system')),
            'DM'                                                                =>  array(__('Dominica','car-rental-booking-system')),
            'DO'                                                                =>  array(__('Dominican Republic','car-rental-booking-system')),
            'EC'                                                                =>  array(__('Ecuador','car-rental-booking-system')),
            'EG'                                                                =>  array(__('Egypt','car-rental-booking-system')),
            'SV'                                                                =>  array(__('El Salvador','car-rental-booking-system')),
            'GQ'                                                                =>  array(__('Equatorial Guinea','car-rental-booking-system')),
            'ER'                                                                =>  array(__('Eritrea','car-rental-booking-system')),
            'EE'                                                                =>  array(__('Estonia','car-rental-booking-system')),
            'ET'                                                                =>  array(__('Ethiopia','car-rental-booking-system')),
            'FK'                                                                =>  array(__('Falkland Islands (Malvinas)','car-rental-booking-system')),
            'FO'                                                                =>  array(__('Faroe Islands','car-rental-booking-system')),
            'FJ'                                                                =>  array(__('Fiji','car-rental-booking-system')),
            'FI'                                                                =>  array(__('Finland','car-rental-booking-system')),
            'FR'                                                                =>  array(__('France','car-rental-booking-system')),
            'GF'                                                                =>  array(__('French Guiana','car-rental-booking-system')),
            'PF'                                                                =>  array(__('French Polynesia','car-rental-booking-system')),
            'TF'                                                                =>  array(__('French Southern Territories','car-rental-booking-system')),
            'GA'                                                                =>  array(__('Gabon','car-rental-booking-system')),
            'GM'                                                                =>  array(__('Gambia','car-rental-booking-system')),
            'GE'                                                                =>  array(__('Georgia','car-rental-booking-system')),
            'DE'                                                                =>  array(__('Germany','car-rental-booking-system')),
            'GH'                                                                =>  array(__('Ghana','car-rental-booking-system')),
            'GI'                                                                =>  array(__('Gibraltar','car-rental-booking-system')),
            'GR'                                                                =>  array(__('Greece','car-rental-booking-system')),
            'GL'                                                                =>  array(__('Greenland','car-rental-booking-system')),
            'GD'                                                                =>  array(__('Grenada','car-rental-booking-system')),
            'GP'                                                                =>  array(__('Guadeloupe','car-rental-booking-system')),
            'GU'                                                                =>  array(__('Guam','car-rental-booking-system')),
            'GT'                                                                =>  array(__('Guatemala','car-rental-booking-system')),
            'GG'                                                                =>  array(__('Guernsey','car-rental-booking-system')),
            'GN'                                                                =>  array(__('Guinea','car-rental-booking-system')),
            'GW'                                                                =>  array(__('Guinea-Bissau','car-rental-booking-system')),
            'GY'                                                                =>  array(__('Guyana','car-rental-booking-system')),
            'HT'                                                                =>  array(__('Haiti','car-rental-booking-system')),
            'HM'                                                                =>  array(__('Heard Island & Mcdonald Islands','car-rental-booking-system')),
            'VA'                                                                =>  array(__('Holy See (Vatican City State)','car-rental-booking-system')),
            'HN'                                                                =>  array(__('Honduras','car-rental-booking-system')),
            'HK'                                                                =>  array(__('Hong Kong','car-rental-booking-system')),
            'HU'                                                                =>  array(__('Hungary','car-rental-booking-system')),
            'IS'                                                                =>  array(__('Iceland','car-rental-booking-system')),
            'IN'                                                                =>  array(__('India','car-rental-booking-system')),
            'ID'                                                                =>  array(__('Indonesia','car-rental-booking-system')),
            'IR'                                                                =>  array(__('Iran, Islamic Republic Of','car-rental-booking-system')),
            'IQ'                                                                =>  array(__('Iraq','car-rental-booking-system')),
            'IE'                                                                =>  array(__('Ireland','car-rental-booking-system')),
            'IM'                                                                =>  array(__('Isle Of Man','car-rental-booking-system')),
            'IL'                                                                =>  array(__('Israel','car-rental-booking-system')),
            'IT'                                                                =>  array(__('Italy','car-rental-booking-system')),
            'JM'                                                                =>  array(__('Jamaica','car-rental-booking-system')),
            'JP'                                                                =>  array(__('Japan','car-rental-booking-system')),
            'JE'                                                                =>  array(__('Jersey','car-rental-booking-system')),
            'JO'                                                                =>  array(__('Jordan','car-rental-booking-system')),
            'KZ'                                                                =>  array(__('Kazakhstan','car-rental-booking-system')),
            'KE'                                                                =>  array(__('Kenya','car-rental-booking-system')),
            'KI'                                                                =>  array(__('Kiribati','car-rental-booking-system')),
            'KR'                                                                =>  array(__('Korea','car-rental-booking-system')),
            'KW'                                                                =>  array(__('Kuwait','car-rental-booking-system')),
            'KG'                                                                =>  array(__('Kyrgyzstan','car-rental-booking-system')),
            'LA'                                                                =>  array(__('Lao People\'s Democratic Republic','car-rental-booking-system')),
            'LV'                                                                =>  array(__('Latvia','car-rental-booking-system')),
            'LB'                                                                =>  array(__('Lebanon','car-rental-booking-system')),
            'LS'                                                                =>  array(__('Lesotho','car-rental-booking-system')),
            'LR'                                                                =>  array(__('Liberia','car-rental-booking-system')),
            'LY'                                                                =>  array(__('Libyan Arab Jamahiriya','car-rental-booking-system')),
            'LI'                                                                =>  array(__('Liechtenstein','car-rental-booking-system')),
            'LT'                                                                =>  array(__('Lithuania','car-rental-booking-system')),
            'LU'                                                                =>  array(__('Luxembourg','car-rental-booking-system')),
            'MO'                                                                =>  array(__('Macao','car-rental-booking-system')),
            'MK'                                                                =>  array(__('Macedonia','car-rental-booking-system')),
            'MG'                                                                =>  array(__('Madagascar','car-rental-booking-system')),
            'MW'                                                                =>  array(__('Malawi','car-rental-booking-system')),
            'MY'                                                                =>  array(__('Malaysia','car-rental-booking-system')),
            'MV'                                                                =>  array(__('Maldives','car-rental-booking-system')),
            'ML'                                                                =>  array(__('Mali','car-rental-booking-system')),
            'MT'                                                                =>  array(__('Malta','car-rental-booking-system')),
            'MH'                                                                =>  array(__('Marshall Islands','car-rental-booking-system')),
            'MQ'                                                                =>  array(__('Martinique','car-rental-booking-system')),
            'MR'                                                                =>  array(__('Mauritania','car-rental-booking-system')),
            'MU'                                                                =>  array(__('Mauritius','car-rental-booking-system')),
            'YT'                                                                =>  array(__('Mayotte','car-rental-booking-system')),
            'MX'                                                                =>  array(__('Mexico','car-rental-booking-system')),
            'FM'                                                                =>  array(__('Micronesia, Federated States Of','car-rental-booking-system')),
            'MD'                                                                =>  array(__('Moldova','car-rental-booking-system')),
            'MC'                                                                =>  array(__('Monaco','car-rental-booking-system')),
            'MN'                                                                =>  array(__('Mongolia','car-rental-booking-system')),
            'ME'                                                                =>  array(__('Montenegro','car-rental-booking-system')),
            'MS'                                                                =>  array(__('Montserrat','car-rental-booking-system')),
            'MA'                                                                =>  array(__('Morocco','car-rental-booking-system')),
            'MZ'                                                                =>  array(__('Mozambique','car-rental-booking-system')),
            'MM'                                                                =>  array(__('Myanmar','car-rental-booking-system')),
            'NA'                                                                =>  array(__('Namibia','car-rental-booking-system')),
            'NR'                                                                =>  array(__('Nauru','car-rental-booking-system')),
            'NP'                                                                =>  array(__('Nepal','car-rental-booking-system')),
            'NL'                                                                =>  array(__('Netherlands','car-rental-booking-system')),
            'AN'                                                                =>  array(__('Netherlands Antilles','car-rental-booking-system')),
            'NC'                                                                =>  array(__('New Caledonia','car-rental-booking-system')),
            'NZ'                                                                =>  array(__('New Zealand','car-rental-booking-system')),
            'NI'                                                                =>  array(__('Nicaragua','car-rental-booking-system')),
            'NE'                                                                =>  array(__('Niger','car-rental-booking-system')),
            'NG'                                                                =>  array(__('Nigeria','car-rental-booking-system')),
            'NU'                                                                =>  array(__('Niue','car-rental-booking-system')),
            'NF'                                                                =>  array(__('Norfolk Island','car-rental-booking-system')),
            'MP'                                                                =>  array(__('Northern Mariana Islands','car-rental-booking-system')),
            'NO'                                                                =>  array(__('Norway','car-rental-booking-system')),
            'OM'                                                                =>  array(__('Oman','car-rental-booking-system')),
            'PK'                                                                =>  array(__('Pakistan','car-rental-booking-system')),
            'PW'                                                                =>  array(__('Palau','car-rental-booking-system')),
            'PS'                                                                =>  array(__('Palestinian Territory, Occupied','car-rental-booking-system')),
            'PA'                                                                =>  array(__('Panama','car-rental-booking-system')),
            'PG'                                                                =>  array(__('Papua New Guinea','car-rental-booking-system')),
            'PY'                                                                =>  array(__('Paraguay','car-rental-booking-system')),
            'PE'                                                                =>  array(__('Peru','car-rental-booking-system')),
            'PH'                                                                =>  array(__('Philippines','car-rental-booking-system')),
            'PN'                                                                =>  array(__('Pitcairn','car-rental-booking-system')),
            'PL'                                                                =>  array(__('Poland','car-rental-booking-system')),
            'PT'                                                                =>  array(__('Portugal','car-rental-booking-system')),
            'PR'                                                                =>  array(__('Puerto Rico','car-rental-booking-system')),
            'QA'                                                                =>  array(__('Qatar','car-rental-booking-system')),
            'RE'                                                                =>  array(__('Reunion','car-rental-booking-system')),
            'RO'                                                                =>  array(__('Romania','car-rental-booking-system')),
            'RU'                                                                =>  array(__('Russian Federation','car-rental-booking-system')),
            'RW'                                                                =>  array(__('Rwanda','car-rental-booking-system')),
            'BL'                                                                =>  array(__('Saint Barthelemy','car-rental-booking-system')),
            'SH'                                                                =>  array(__('Saint Helena','car-rental-booking-system')),
            'KN'                                                                =>  array(__('Saint Kitts And Nevis','car-rental-booking-system')),
            'LC'                                                                =>  array(__('Saint Lucia','car-rental-booking-system')),
            'MF'                                                                =>  array(__('Saint Martin','car-rental-booking-system')),
            'PM'                                                                =>  array(__('Saint Pierre And Miquelon','car-rental-booking-system')),
            'VC'                                                                =>  array(__('Saint Vincent And Grenadines','car-rental-booking-system')),
            'WS'                                                                =>  array(__('Samoa','car-rental-booking-system')),
            'SM'                                                                =>  array(__('San Marino','car-rental-booking-system')),
            'ST'                                                                =>  array(__('Sao Tome And Principe','car-rental-booking-system')),
            'SA'                                                                =>  array(__('Saudi Arabia','car-rental-booking-system')),
            'SN'                                                                =>  array(__('Senegal','car-rental-booking-system')),
            'RS'                                                                =>  array(__('Serbia','car-rental-booking-system')),
            'SC'                                                                =>  array(__('Seychelles','car-rental-booking-system')),
            'SL'                                                                =>  array(__('Sierra Leone','car-rental-booking-system')),
            'SG'                                                                =>  array(__('Singapore','car-rental-booking-system')),
            'SK'                                                                =>  array(__('Slovakia','car-rental-booking-system')),
            'SI'                                                                =>  array(__('Slovenia','car-rental-booking-system')),
            'SB'                                                                =>  array(__('Solomon Islands','car-rental-booking-system')),
            'SO'                                                                =>  array(__('Somalia','car-rental-booking-system')),
            'ZA'                                                                =>  array(__('South Africa','car-rental-booking-system')),
            'GS'                                                                =>  array(__('South Georgia And Sandwich Isl.','car-rental-booking-system')),
            'ES'                                                                =>  array(__('Spain','car-rental-booking-system')),
            'LK'                                                                =>  array(__('Sri Lanka','car-rental-booking-system')),
            'SD'                                                                =>  array(__('Sudan','car-rental-booking-system')),
            'SR'                                                                =>  array(__('Suriname','car-rental-booking-system')),
            'SJ'                                                                =>  array(__('Svalbard And Jan Mayen','car-rental-booking-system')),
            'SZ'                                                                =>  array(__('Swaziland','car-rental-booking-system')),
            'SE'                                                                =>  array(__('Sweden','car-rental-booking-system')),
            'CH'                                                                =>  array(__('Switzerland','car-rental-booking-system')),
            'SY'                                                                =>  array(__('Syrian Arab Republic','car-rental-booking-system')),
            'TW'                                                                =>  array(__('Taiwan','car-rental-booking-system')),
            'TJ'                                                                =>  array(__('Tajikistan','car-rental-booking-system')),
            'TZ'                                                                =>  array(__('Tanzania','car-rental-booking-system')),
            'TH'                                                                =>  array(__('Thailand','car-rental-booking-system')),
            'TL'                                                                =>  array(__('Timor-Leste','car-rental-booking-system')),
            'TG'                                                                =>  array(__('Togo','car-rental-booking-system')),
            'TK'                                                                =>  array(__('Tokelau','car-rental-booking-system')),
            'TO'                                                                =>  array(__('Tonga','car-rental-booking-system')),
            'TT'                                                                =>  array(__('Trinidad And Tobago','car-rental-booking-system')),
            'TN'                                                                =>  array(__('Tunisia','car-rental-booking-system')),
            'TR'                                                                =>  array(__('Turkey','car-rental-booking-system')),
            'TM'                                                                =>  array(__('Turkmenistan','car-rental-booking-system')),
            'TC'                                                                =>  array(__('Turks And Caicos Islands','car-rental-booking-system')),
            'TV'                                                                =>  array(__('Tuvalu','car-rental-booking-system')),
            'UG'                                                                =>  array(__('Uganda','car-rental-booking-system')),
            'UA'                                                                =>  array(__('Ukraine','car-rental-booking-system')),
            'AE'                                                                =>  array(__('United Arab Emirates','car-rental-booking-system')),
            'GB'                                                                =>  array(__('United Kingdom','car-rental-booking-system')),
            'US'                                                                =>  array(__('United States','car-rental-booking-system')),
            'UM'                                                                =>  array(__('United States Outlying Islands','car-rental-booking-system')),
            'UY'                                                                =>  array(__('Uruguay','car-rental-booking-system')),
            'UZ'                                                                =>  array(__('Uzbekistan','car-rental-booking-system')),
            'VU'                                                                =>  array(__('Vanuatu','car-rental-booking-system')),
            'VE'                                                                =>  array(__('Venezuela','car-rental-booking-system')),
            'VN'                                                                =>  array(__('Viet Nam','car-rental-booking-system')),
            'VG'                                                                =>  array(__('Virgin Islands, British','car-rental-booking-system')),
            'VI'                                                                =>  array(__('Virgin Islands, U.S.','car-rental-booking-system')),
            'WF'                                                                =>  array(__('Wallis And Futuna','car-rental-booking-system')),
            'EH'                                                                =>  array(__('Western Sahara','car-rental-booking-system')),
            'YE'                                                                =>  array(__('Yemen','car-rental-booking-system')),
            'ZM'                                                                =>  array(__('Zambia','car-rental-booking-system')),
            'ZW'                                                                =>  array(__('Zimbabwe','car-rental-booking-system'))
        );    
		
		return($country);
    }
    
    /**************************************************************************/
    
    function getCountry($country=null)
    {
        if(is_null($country)) return($this->country);
        else return($this->country[$country]);
    }
    
    /**************************************************************************/
    
    function isCountry($index)
    {
        return(array_key_exists($index,$this->country));
    }
    
    /**************************************************************************/
    
    function getCountryName($index)
    {
        return($this->country[$index][0]);
    }
    
    /**************************************************************************/
}

/******************************************************************************/
/******************************************************************************/